#	conquer: Copyright 1991 by Edward M Barlow and Adam Bryant
#		 All Rights Reserved 
#
#	This Makefile should not need changing.
#
#	Please report any problems that you encounter with any of the
#	Makefiles.  If any problems develop while compiling, or if any
#	files but Makefile.top and header.h files need editing,
#	please send me mail.
#			adb@cs.bu.edu
#			adb@bucsf.bu.edu
#       		adb@bu.edu
#
# SDL2 Display Layer (Phase 4)
#
# Added SDL2 support to the original curses-based display layer.
# Use `make build` to build with SDL2, `make build_curses` to use curses.

#	All of the default settings
MAKE	= %%MAKE%%
MKDPND	= %%MKDPND%%
MKDIR	= %%MKDIR%%
SHELL	= %%SHELL%%
CC	= %%CC%%
CD	= %%CD%%
RM      = %%RM%%
CP	= %%CP%%
MV	= %%MV%%
ECHO	= %%ECHO%%
STRIP	= %%STRIP%%
NULL	= %%NULL%%
TOUCH	= %%TOUCH%%
CHOWN	= %%CHOWN%%
CHMOD	= %%CHMOD%%
LIBS	= %%LIBS%%
SYSFLG	= %%SYSFLG%%
CFLAGS	= -I${INCDIR} ${SYSFLG} -DPLATFORM_LINUX -lSDL2 -lSDL2_ttf
CKFLAGS	= %%CKFLAGS%%
TOPDIR	= %%TOPDIR%%
DATADIR	= %%DATADIR%%
BINDIR	= %%BINDIR%%
INCDIR	= %%TOPDIR%%/%%INCDIR%%
SRCDIR	= %%TOPDIR%%/%%SRCDIR%%
AUXDIR	= %%TOPDIR%%/%%AUXDIR%%
DOCDIR	= %%TOPDIR%%/%%DOCDIR%%
CQUER	= %%CQUER%%
CQRUN	= %%CQRUN%%
CQSORT	= %%CQSORT%%
CXTRACT	= %%CXTRACT%%
GFILS	= %%GFILS%%
AFILS	= %%AFILS%%
XFILS	= %%XFILS%%

#	SDL2 display object (Phase 4)
SDL2_DISPLAY_OBJS	= sdl2/SDL2_display.o

#	lists of object files
AOBJS	= %%AOBJS%% jointA.o
GOBJS	= %%GOBJS%% jointG.o sdl2/SDL2_display.o
XOBJS	= %%XOBJS%%

#
#	Makefile specific variables
#

#	preprocessor definitions
CPPFLG	= -I${INCDIR} ${SYSFLG}

#	list of support files to be installed
SUPPORT	= nations

#
#	Building and Installation Procedures
#
all:	
	@${ECHO} "Use one of:"
	@${ECHO} "   make build       -- build everything with SDL2"
	@${ECHO} "   make build_curses -- build with curses"
	@${ECHO} "   make install     -- install everything"
	@${ECHO} "   make clean       -- clean up everything"
	@${ECHO} "   make clobber     -- really do some cleanup"

#
build:	${CQUER} ${CQRUN}
	@${ECHO} Done with build in Src

#
build_curses:	${CQUER}_curses ${CQRUN}_curses
	@${ECHO} Done with curses build in Src

#
install:	in${CQUER} in${CQRUN} insupport
	@${ECHO} Done with install in Src

#
#	installation of support files
insupport:	${SUPPORT}
	-${MKDIR} ${DATADIR}
	${CHOWN} ${DATADIR}
	${CHMOD} 700 ${DATADIR}
	${CP} ${SUPPORT} ${DATADIR}
	${CHOWN} ${DATADIR}/*
	${TOUCH} insupport

#
#	Makefile specific dependencies and rules

#	User interface
${CQUER}:	${GOBJS} ${XOBJS}
	@${ECHO} ${CQUER} object files done...
	@${ECHO} === Compiling User Interface ===
	${CC} ${CFLAGS} -o ${CQUER} ${GOBJS} ${XOBJS} ${LIBS}

#	SDL2 display (Phase 4)
sdl2/SDL2_display.o: sdl2/SDL2_display.c
	@${ECHO} ${CQUER} SDL2_display object files done...
	${CC} ${CFLAGS} -I./sdl2 -o $@ $<

#	User interface (curses)
${CQUER}_curses:	${GOBJS}_curses ${XOBJS}
	@${ECHO} ${CQUER}_curses object files done...
	@${ECHO} === Compiling User Interface (curses) ===
	${CC} ${CFLAGS} -I${INCDIR} -DPLATFORM_LINUX -lncurses -lcrypt -o ${CQUER}_curses ${GOBJS}_curses ${XOBJS}

#	Curses display (stub for curses build)
sdl2/SDL2_display.o_curses: sdl2/SDL2_display.c
	@${ECHO} ${CQUER}_curses SDL2_display object files done...
	@# Stub for curses build (same source, different flags)
	${CC} ${CFLAGS} -I./sdl2 -DPLATFORM_LINUX -lSDL2 -lSDL2_ttf -lncurses -o $@ $<

#	User interface (curses)
${CQRUN}:	${AOBJS} ${XOBJS}
	@${ECHO} ${CQRUN} object files done...
	@${ECHO} === Compiling Admin Interface ===
	${CC} ${CFLAGS} -o ${CQRUN} ${AOBJS} ${XOBJS} ${LIBS}

#	Curses admin (stub for curses build)
sdl2/SDL2_display.o_curses: sdl2/SDL2_display.c
	@${ECHO} ${CQRUN}_curses SDL2_display object files done...
	@# Stub for curses build (same source, different flags)
	${CC} ${CFLAGS} -I./sdl2 -DPLATFORM_LINUX -lSDL2 -lSDL2_ttf -lncurses -o $@ $<

#	Curses admin (stub for curses build)
${CQRUN}_curses:	${AOBJS}_curses ${XOBJS}
	@${ECHO} ${CQRUN}_curses object files done...
	@${ECHO} === Compiling Admin Interface (curses) ===
	${CC} ${CFLAGS} -I${INCDIR} -DPLATFORM_LINUX -lncurses -lcrypt -o ${CQRUN}_curses ${AOBJS}_curses ${XOBJS}

#	SDL2 display (Phase 4)
sdl2/SDL2_display.o: sdl2/SDL2_display.c
	@${ECHO} ${CQRUN} SDL2_display object files done...
	${CC} ${CFLAGS} -I./sdl2 -o $@ $<

#	SDL2 display (Phase 4)
sdl2/SDL2_display.o_curses: sdl2/SDL2_display.c
	@${ECHO} ${CQRUN}_curses SDL2_display object files done...
	@# Stub for curses build (same source, different flags)
	${CC} ${CFLAGS} -I./sdl2 -DPLATFORM_LINUX -lSDL2 -lSDL2_ttf -lncurses -o $@ $<

#
clean:
	rm -f *.o sdl2/SDL2_display.o ${CQUER} ${CQRUN} ${CQUER}_curses ${CQRUN}_curses conquer conqrun
	rm -f *.exe *.o_curses sdl2/SDL2_display.o_curses

#
clobber: clean
	rm -rf sdist sdist-* .sdist
	rm -f *.o *.exe *.o_curses *.tar.gz *.tgz *.zip
	rm -f *.tar *.t *.tar.* *.tar.gz *.tgz

.PHONY: clean clobber build build_curses

# SDL2 Display Layer (Phase 4)
# Note: Add -lSDL2 -lSDL2_ttf to CFLAGS when you link against SDL2_display.o
# Example: conquer: mainG.o $(GAME_OBJS)
#          $(CC) $(CFLAGS) -o $@ $^ -lncurses -lcrypt -lSDL2 -lSDL2_ttf

